module.exports = {
  'uno': 'uno',
  'mega': 'mega:cpu=atmega2560',
  'leonardo': 'leonardo',
  'micro': 'micro',
  'nano' : 'nano:cpu=atmega328',
  'diecimila': 'diecimila',
  'yun': 'yun',
  'pro': 'pro',
  'adkmega':'ADKmegaADK',
  'esplora': 'esplora',
  'mini': 'mini',
  'ethernet': 'ethernet',
  'fio': 'fio',
  'bt':'bt',
  'LilyPadUSB': 'LilyPadUSB',
  'lilypad': 'lilypad',
  'atmegang': 'atmegang',
  'robotControl': 'robotControl',
  'robotMotor': 'robotMotor',
  'gemma': 'gemma'
};
